server:
  port: 8082

name: abc

# 对象
person:
  name: zhangsan
  #  name: ${name} #zhangsan
  age: 20
  address:
    - beijing
    - shanghai

address:
  - beijing
  - shanghai

# 纯量
msg1: 'hello \n world' # 不会识别转义字符，会以原样输出
msg2: "hello \n world" # 会识别转义字符