# spring
spring:
  # dataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/secruity_test?
      useUnicode=true&
      characterEncoding=utf-8&
      useSSL=true&
      serverTimezone=Asia/Shanghai
      # serverTimezone=UTC
    # 此处因为插入数据库的时间有差异，所以强制了时区，暂时如此处理
    username: root
    password: root
  # jpa
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html

server:
  port: 8888
