
spring:
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    encoding: UTF-8

  #jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/myscoremanage?
         serverTimezone=UTC&
         useUnicode=true&
         characterEncoding=utf-8&
         useSSL=true
    username: root
    password: root


#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: io.github.zemise.sms.entity

# 日志
logging:
  level:
    root: INFO
    # 配置SQL打印
    io.github.zemise.sms.mapper: debug
  file:
    name: student-management-system/spring_log.log



#docker run --restart always \
#-d -i -p 3306:3306 \
#-e MYSQL_ROOT_PASSWORD=root \
#-d --name mysql_main \
#-v /Users/zemise/Desktop/001_AllCode/Docker/mysql/mysql_main/mysql_data:/var/lib/mysql \
#-e MYSQL_DATABASE=myscoremanage \
#mysql:latest


