# datasource
spring:
  datasource:
    url: jdbc:mysql://hostname:1106/sys
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml # mapper的映射文件路径
  type-aliases-package: io.github.zemise.springbootmybaits.domain
  # config-location: #  指定mybatis的核心配置文件